services:
  api:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm start:dev
    ports:
      - "${PORT:-5553}:${PORT:-5553}"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PORT=${PORT:-5553}
    env_file:
      - .env
    restart: unless-stopped